{% set name = "prolfqua" %}
{% set version = "1.0.0" %}

package:
    name: "r-{{ name|lower }}"
    version: "{{ version }}"

build:
    number: 0
    noarch: generic
    rpaths:
        - lib/
        - lib/R/lib/

source:
    path: ../

requirements:
    host:
        - r-base >=4.1
    run:
        - r-base >=4.1
        - r-bookdown
        - r-broom
        - r-conflicted
        - r-devtools
        - r-dplyr
        - r-DT
        - r-forcats
        - r-ggplot2
        - r-ggbeeswarm
        - r-ggrepel
        - r-ggridges
        - r-ggpubr
        - r-htmlwidgets
        - r-lme4
        - r-lmerTest
        - r-logger
        - r-MASS
        - r-multcomp
        - r-pheatmap
        - r-plotly
        - r-progress
        - r-purrr
        - r-readr
        - r-readxl
        - r-rlang
        - r-stringr
        - r-tidyr
        - r-tibble
        - r-yaml
        - r-writexl
        - r-corrplot
        - r-docopt
        - r-knitr
        - r-pROC
        - r-rmarkdown
        - r-remotes
        - r-testthat
        - bioconductor-limma >=3.50.0
        - bioconductor-summarizedexperiment
        - bioconductor-msstats
        - bioconductor-proda
        - bioconductor-s4vectors
        - bioconductor-vsn
test:
    commands:
        - $R -e "library(prolfqua)"

about:
    home: "https://github.com/cpanse/prolfqua"
    license: MIT
    summary: Proteomics Label Free Quantification
extra:
    recipe-maintainers:
        - wolski
        - cpanse
